// apps/react-examples/src/examples/between-value-types.tsx
import { motion } from 'motion/react'
import { useState } from 'react'

export const meta = {
  slug: 'between-value-types',
  title: 'Between value types',
  category: 'animations',
  description: 'Switching between px and % widths — motion handles the unit.',
  tag: 'units',
} as const

export default function BetweenValueTypes() {
  const [wide, setWide] = useState(false)

  return (
    <button
      onClick={() => setWide((v) => !v)}
      className="h-3 w-56 overflow-hidden rounded-full bg-card"
    >
      <motion.div
        className="h-full rounded-full bg-grad-rose"
        animate={{ width: wide ? '100%' : '40px' }}
        transition={{ type: 'spring', stiffness: 200, damping: 22 }}
      />
    </button>
  )
}

// apps/solidjs-motion/src/examples/between-value-types.tsx
import { motion } from 'solidjs-motion'
import { createSignal } from 'solid-js'

export const meta = {
  slug: 'between-value-types',
  title: 'Between value types',
  category: 'animations',
  description: 'Switching between px and % widths — motion handles the unit.',
  tag: 'units',
} as const

export default function BetweenValueTypes() {
  const [wide, setWide] = createSignal(false)

  return (
    <button
      onClick={() => setWide((v) => !v)}
      class="h-3 w-56 overflow-hidden rounded-full bg-card"
    >
      <motion.div
        class="h-full rounded-full bg-grad-rose"
        animate={{ width: wide() ? '100%' : '40px' }}
        transition={{ type: 'spring', stiffness: 200, damping: 22 }}
      />
    </button>
  )
}
